In [6]:
import pandas as pd
import numpy as np

In [8]:
data =pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\supervised learning\\Naive bayes\\playtennis.csv")
data.sample(5)

      Outlook Temperature Humidity    Wind PlayTennis
11   Overcast         Hot   Normal    Weak        Yes
45       Rain        Cool     High  Strong         No
86   Overcast        Mild      NaN  Strong        Yes
155     Sunny        Cool     High  Strong         No
132      Rain         Hot     High  Strong         No

In [12]:
data.isnull().mean()*100

Outlook        0.0
Temperature    0.0
Humidity       4.5
Wind           5.0
PlayTennis     0.0
dtype: float64

In [14]:
# Fill categorical missing values with the mode
data["Humidity"].fillna(data["Humidity"].mode()[0], inplace=True)
data["Wind"].fillna(data["Wind"].mode()[0], inplace=True)

C:\Users\sampada\AppData\Local\Temp\ipykernel_16872\4289446773.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Humidity"].fillna(data["Humidity"].mode()[0], inplace=True)
C:\Users\sampada\AppData\Local\Temp\ipykernel_16872\4289446773.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Wind"].fillna(data["Wind"].mode()[0], inplace=True)

In [16]:
data.isnull().mean()*100

Outlook        0.0
Temperature    0.0
Humidity       0.0
Wind           0.0
PlayTennis     0.0
dtype: float64

In [22]:
data.duplicated().sum()

154

In [24]:
data.drop_duplicates(inplace=True)

In [26]:
data.duplicated().sum()

0

In [30]:
data.sample(10)

      Outlook Temperature Humidity    Wind PlayTennis
19       Rain         Hot   Normal    Weak         No
22   Overcast        Cool     High    Weak         No
3        Rain        Mild     High  Strong         No
21       Rain        Cool   Normal  Strong         No
29       Rain        Cool     High  Strong         No
153      Rain        Cool     High    Weak        Yes
32       Rain         Hot     High    Weak         No
65       Rain        Mild   Normal  Strong         No
4        Rain         Hot   Normal    Weak        Yes
117  Overcast        Cool   Normal  Strong        Yes

In [ ]:
# problem 1
#outlook = Rain,Temperature = Hot,Humidity=High,wind=weak
# play tennis yes or no?

In [ ]:
#solution
#P(Yes/Rain,Hot,High,weak)=P(Rain/yes)* P(Hot/yes)* P(high/yes) * P(weak/yes)* P(yes)
#P(No/Rain,Hot,High,weak)=P(Rain/no)* P(Hot/no)* P(high/no) * P(weak/no)* P(no)

In [ ]:
# Traing phase:Naive bayes create the look up table storeit in dict

In [38]:
data.shape

(46, 5)

In [32]:
data['PlayTennis'].value_counts()

PlayTennis
Yes    25
No     21
Name: count, dtype: int64

In [84]:
Py=25/46
Pn=21/46
print(py)
print(pn)

0.5434782608695652
0.45652173913043476

In [86]:
pd.crosstab(data['Outlook'],data['PlayTennis'])

PlayTennis  No  Yes
Outlook
Overcast     3   12
Rain        11    5
Sunny        7    8

In [88]:
Pon = 3/21
Prn = 11/21
Psn =7/21

Poy = 12/25
Pry = 5/25
Psy = 8/25

In [90]:
pd.crosstab(data['Temperature'],data['PlayTennis'])

PlayTennis   No  Yes
Temperature
Cool          8    8
Hot           6    7
Mild          7   10

In [92]:
Pcn=8/21
Phn=6/21
Pnn=7/21

Pcy=8/25
Phy=7/25
Pmy=10/25

In [94]:
pd.crosstab(data['Humidity'],data['PlayTennis'])

PlayTennis  No  Yes
Humidity
High        13   10
Normal       8   15

In [96]:
Phighn =13/21
Pnormaln = 8/21

Phighy=10/25
Pnormaly=15/25

In [98]:
pd.crosstab(data['Wind'],data['PlayTennis'])

PlayTennis  No  Yes
Wind
Strong      11   10
Weak        10   15

In [100]:
Pstrongn =11/21
Pweakn =10/21

Pstrongy =10/25
Pweaky =15/25

In [106]:
# Testing phase:
# problem 1
#outlook = Rain,Temperature = Hot,Humidity=High,wind=weak
Pyes = Py * Pry * Phy * Phighy * Pweaky
print(Pyes)

0.007304347826086957

In [104]:
Pno =Pn * Prn * Phn * Phighn * Pweakn
print(Pno)

0.020140561400543655

In [ ]:
# probability of no is > than probability of yes so we conclude play tennis is no