## Series

In [3]:
import pandas as pd

In [7]:
x = [1,2,3,4,5]
var = pd.Series(x)
print(var)
print(type(var))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
x = [3,4,5]
var = pd.Series(x,index = ['a','b','c'],dtype = float,name = 'python')
print(var)

a    3.0
b    4.0
c    5.0
Name: python, dtype: float64

In [21]:
dict = {'name':['pytho','java','c','c++'],'rank':[1,2,4,3]}
var = pd.Series(dict)
print(var)

name    [pytho, java, c, c++]
rank             [1, 2, 4, 3]
dtype: object

In [27]:
x = pd.Series(12)
print(x)

0    12
dtype: int64

In [25]:
x = pd.Series(12,index = [1,2,3,4,5])
print(x)

1    12
2    12
3    12
4    12
5    12
dtype: int64

In [29]:
s1 = pd.Series(12,index = [1,2,3,4,5])
s2 = pd.Series(12,index = [3,4,5])
print(s1*s2)

1      NaN
2      NaN
3    144.0
4    144.0
5    144.0
dtype: float64

### DataFrames

In [6]:
import pandas as pd

In [8]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d)
print(type(var))
print(var)

<class 'pandas.core.frame.DataFrame'>
   a   b
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

In [33]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d,index=['a','s','d','f','g'],columns=['a'])
print(type(var))
print(var)
print(var['a']['f'])

<class 'pandas.core.frame.DataFrame'>
   a
a  1
s  2
d  3
f  4
g  5
4

In [35]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d)
print(var)
print(var['b'][2])

   a   b
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
13

In [39]:
ls = [[1,2,3,4],[21,22,23,24]] # list of list
var =pd.DataFrame(ls)
print(type(var))
print(var)

<class 'pandas.core.frame.DataFrame'>
    0   1   2   3
0   1   2   3   4
1  21  22  23  24

In [43]:
list_1 = {'a':pd.Series([1,2,3,4]),'b':pd.Series([31,32,33,34])}
var = pd.DataFrame(list_1)
print(var)
print(type(var))

   a   b
0  1  31
1  2  32
2  3  33
3  4  34
<class 'pandas.core.frame.DataFrame'>

### Airthmetic operation in pandas

In [60]:
var_1 = pd.DataFrame({'a':[1,11,21,31],'b':[10,20,30,40]})
var_1

    a   b
0   1  10
1  11  20
2  21  30
3  31  40

In [74]:

var_1['c'] = var_1['a']+var_1['b']
var_1['d'] = var_1['a']-var_1['b']
var_1['e'] = var_1['a']*var_1['b']
var_1['f'] = var_1['a']/ var_1['b']
var_1

    a   b   c  d     e      f
0   1  10  11 -9    10  0.100
1  11  20  31 -9   220  0.550
2  21  30  51 -9   630  0.700
3  31  40  71 -9  1240  0.775

In [76]:
var_1['new']=var_1['b']<= 20
var_1

    a   b   c  d     e      f    new
0   1  10  11 -9    10  0.100   True
1  11  20  31 -9   220  0.550   True
2  21  30  51 -9   630  0.700  False
3  31  40  71 -9  1240  0.775  False

### insert

In [131]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[31,32,33,34]})
print(var)
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

In [133]:
var.insert(1,'python',var['a'])
var

   a  python   b
0  1       1  31
1  2       2  32
2  3       3  33
3  4       4  34

In [135]:
var1 = var.pop('python')
var1

0    1
1    2
2    3
3    4
Name: python, dtype: int64

In [137]:
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

In [141]:
var.insert(1,'hey',[11,44,66,77])
var

   a  hey   b
0  1   11  31
1  2   44  32
2  3   66  33
3  4   77  34

In [151]:

del var['hey']

In [153]:
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34