## Series

In [9]:
import pandas as pd

In [7]:
x = [1,2,3,4,5]
var = pd.Series(x)
print(var)
print(type(var))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [15]:
x = [3,4,5]
var = pd.Series(x,index = ['a','b','c'],dtype = float,name = 'python')
print(var)

a    3.0
b    4.0
c    5.0
Name: python, dtype: float64

In [21]:
dict = {'name':['pytho','java','c','c++'],'rank':[1,2,4,3]}
var = pd.Series(dict)
print(var)

name    [pytho, java, c, c++]
rank             [1, 2, 4, 3]
dtype: object

In [27]:
x = pd.Series(12)
print(x)

0    12
dtype: int64

In [25]:
x = pd.Series(12,index = [1,2,3,4,5])
print(x)

1    12
2    12
3    12
4    12
5    12
dtype: int64

In [29]:
s1 = pd.Series(12,index = [1,2,3,4,5])
s2 = pd.Series(12,index = [3,4,5])
print(s1*s2)

1      NaN
2      NaN
3    144.0
4    144.0
5    144.0
dtype: float64

### DataFrames

In [6]:
import pandas as pd

In [8]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d)
print(type(var))
print(var)

<class 'pandas.core.frame.DataFrame'>
   a   b
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15

In [33]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d,index=['a','s','d','f','g'],columns=['a'])
print(type(var))
print(var)
print(var['a']['f'])

<class 'pandas.core.frame.DataFrame'>
   a
a  1
s  2
d  3
f  4
g  5
4

In [35]:
d = {'a':[1,2,3,4,5],'b':[11,12,13,14,15]}
var = pd.DataFrame(d)
print(var)
print(var['b'][2])

   a   b
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
13

In [39]:
ls = [[1,2,3,4],[21,22,23,24]] # list of list
var =pd.DataFrame(ls)
print(type(var))
print(var)

<class 'pandas.core.frame.DataFrame'>
    0   1   2   3
0   1   2   3   4
1  21  22  23  24

In [43]:
list_1 = {'a':pd.Series([1,2,3,4]),'b':pd.Series([31,32,33,34])}
var = pd.DataFrame(list_1)
print(var)
print(type(var))

   a   b
0  1  31
1  2  32
2  3  33
3  4  34
<class 'pandas.core.frame.DataFrame'>

### Airthmetic operation in pandas

In [60]:
var_1 = pd.DataFrame({'a':[1,11,21,31],'b':[10,20,30,40]})
var_1

    a   b
0   1  10
1  11  20
2  21  30
3  31  40

In [74]:

var_1['c'] = var_1['a']+var_1['b']
var_1['d'] = var_1['a']-var_1['b']
var_1['e'] = var_1['a']*var_1['b']
var_1['f'] = var_1['a']/ var_1['b']
var_1

    a   b   c  d     e      f
0   1  10  11 -9    10  0.100
1  11  20  31 -9   220  0.550
2  21  30  51 -9   630  0.700
3  31  40  71 -9  1240  0.775

In [76]:
var_1['new']=var_1['b']<= 20
var_1

    a   b   c  d     e      f    new
0   1  10  11 -9    10  0.100   True
1  11  20  31 -9   220  0.550   True
2  21  30  51 -9   630  0.700  False
3  31  40  71 -9  1240  0.775  False

### insert

In [131]:
var = pd.DataFrame({'a':[1,2,3,4],'b':[31,32,33,34]})
print(var)
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

In [133]:
var.insert(1,'python',var['a'])
var

   a  python   b
0  1       1  31
1  2       2  32
2  3       3  33
3  4       4  34

In [135]:
var1 = var.pop('python')
var1

0    1
1    2
2    3
3    4
Name: python, dtype: int64

In [137]:
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

In [141]:
var.insert(1,'hey',[11,44,66,77])
var

   a  hey   b
0  1   11  31
1  2   44  32
2  3   66  33
3  4   77  34

In [151]:

del var['hey']

In [153]:
var

   a   b
0  1  31
1  2  32
2  3  33
3  4  34

## Read csv file

In [11]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv")
csv_1

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [164]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv",nrows=1)
csv_1

   PassengerId  Survived
0          892         0

In [166]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv",usecols=[1])
csv_1

     Survived
0           0
1           1
2           0
3           0
4           1
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]

In [168]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv",skiprows = [2])
csv_1

     PassengerId  Survived
0            892         0
1            894         0
2            895         0
3            896         1
4            897         0
..           ...       ...
412         1305         0
413         1306         1
414         1307         0
415         1308         0
416         1309         0

[417 rows x 2 columns]

In [196]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv",index_col='PassengerId')
csv_1

             Survived
PassengerId
892                 0
893                 1
894                 0
895                 0
896                 1
...               ...
1305                0
1306                1
1307                0
1308                0
1309                0

[418 rows x 1 columns]

In [192]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\gender_submission.csv",header=None,prefix='col') #if header is none 
csv_1

TypeError: read_csv() got an unexpected keyword argument 'Prefix'

### drop

In [21]:
csv_1 = csv_1.drop('Survived', axis=1)

KeyError: "['Survived'] not found in axis"

In [24]:
csv_1.head()

   PassengerId
0          892
1          893
2          894
3          895
4          896

In [15]:
csv_1.drop(0,axis = 0)

     PassengerId  Survived
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[417 rows x 2 columns]

### dropna and fillna

In [28]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90,92.0,Bhaktapur,Master
48,49,Yogesh,20.0,Male,3.0,79.0,77,78.0,Dharan,High School
49,50,Pratima,18.0,Female,4.0,89.0,88,90.0,Kathmandu,Bachelor

In [33]:
csv_1.dropna()

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85,88.0,Kathmandu,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84,86.0,Pokhara,Bachelor
8,9,Pooja,20.0,Female,3.0,75.0,72,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80,82.0,Dharan,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83,85.0,Kathmandu,Bachelor
15,16,Sabina,20.0,Female,6.0,96.0,95,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81,80.0,Butwal,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77,76.0,Butwal,High School
25,26,Manisha,19.0,Female,6.0,97.0,96,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78,79.0,Bhaktapur,High School
35,36,Priyanka,19.0,Female,6.0,98.0,97,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86,87.0,Chitwan,Bachelor
48,49,Yogesh,20.0,Male,3.0,79.0,77,78.0,Dharan,High School
49,50,Pratima,18.0,Female,4.0,89.0,88,90.0,Kathmandu,Bachelor

In [39]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90,92.0,Bhaktapur,Master
48,49,Yogesh,20.0,Male,3.0,79.0,77,78.0,Dharan,High School
49,50,Pratima,18.0,Female,4.0,89.0,88,90.0,Kathmandu,Bachelor

In [37]:
csv_1.dropna(axis=1)

    Student_ID      Name  Gender  Math_Score       City Parent_Education
0            1    Anisha  Female          85  Kathmandu         Bachelor
1            2       Ram    Male          78    Pokhara           Master
2            3      Sita  Female          92     Butwal         Bachelor
3            4      Hari    Male          75   Lalitpur      High School
4            5      Gita  Female          94  Bhaktapur           Master
5            6    Bikash    Male          65    Chitwan         Bachelor
6            7     Nisha  Female          84    Pokhara         Bachelor
7            8     Rajan    Male          89  Kathmandu           Master
8            9     Pooja  Female          72     Butwal      High School
9           10     Suman    Male          80     Dharan         Bachelor
10          11     Kiran    Male          76   Lalitpur         Bachelor
11          12      Rita  Female          91  Bhaktapur           Master
12          13     Ashok    Male          74    Chitwan      High School
13          14      Mina  Female          83  Kathmandu         Bachelor
14          15    Deepak    Male          68    Pokhara      High School
15          16    Sabina  Female          95     Dharan           Master
16          17    Ramesh    Male          81     Butwal         Bachelor
17          18    Sarita  Female          88   Lalitpur         Bachelor
18          19   Prakash    Male          73    Chitwan      High School
19          20     Rekha  Female          86  Bhaktapur           Master
20          21      Ajay    Male          69     Dharan         Bachelor
21          22     Sneha  Female          92  Kathmandu           Master
22          23     Nabin    Male          84    Pokhara         Bachelor
23          24    Sunita  Female          77     Butwal      High School
24          25     Rohit    Male          78   Lalitpur         Bachelor
25          26   Manisha  Female          96  Bhaktapur           Master
26          27     Arjun    Male          70    Chitwan      High School
27          28    Kabita  Female          89     Dharan         Bachelor
28          29    Suresh    Male          79  Kathmandu         Bachelor
29          30    Asmita  Female          85    Pokhara           Master
30          31     Binod    Male          67     Butwal      High School
31          32    Roshni  Female          93   Lalitpur           Master
32          33     Shyam    Male          82    Chitwan         Bachelor
33          34     Alina  Female          78  Bhaktapur      High School
34          35    Dinesh    Male          74     Dharan         Bachelor
35          36  Priyanka  Female          97  Kathmandu           Master
36          37     Madan    Male          71    Pokhara      High School
37          38    Shreya  Female          90     Butwal         Bachelor
38          39    Ganesh    Male          81   Lalitpur         Bachelor
39          40     Laxmi  Female          75    Chitwan      High School
40          41     Niraj    Male          66  Bhaktapur         Bachelor
41          42    Sushma  Female          94     Dharan           Master
42          43       Tej    Male          85  Kathmandu         Bachelor
43          44    Reshma  Female          80    Pokhara      High School
44          45     Kamal    Male          72     Butwal         Bachelor
45          46     Aarti  Female          95   Lalitpur           Master
46          47     Suraj    Male          86    Chitwan         Bachelor
47          48   Namrata  Female          90  Bhaktapur           Master
48          49    Yogesh    Male          77     Dharan      High School
49          50   Pratima  Female          88  Kathmandu         Bachelor

In [49]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [47]:
csv_1.dropna(how ='any') # drop the row having all null in this case 48

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [51]:
csv_1.dropna(subset=['Study_Hours']) #droping null value in this column

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [57]:
csv_1.dropna(thresh= 1) # dropping null value from the column having single null

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

## fillna

In [60]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [62]:
csv_1.fillna('python')#fill null with python

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,python,85.0,78.0,python,Pokhara,Master
2,3,Sita,python,Female,5.0,python,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,python,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,python,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,python,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,python,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,python,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,python,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,python,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,python,python,python,python,python,python,python,python,python
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [66]:
csv_1.fillna({'Age':'old','Attendance':'Daily'}) #fill null with data per column

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,old,Female,5.0,Daily,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,old,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,Daily,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,old,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,old,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,old,NaN,NaN,Daily,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [68]:
csv_1.fillna(method='ffill') #forward fill

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\3837387559.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method='ffill') #forward fill

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.0,85.0,78.0,88.0,Pokhara,Master
2,3,Sita,19.0,Female,5.0,85.0,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.0,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.0,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,87.0,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,22.0,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,3.0,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,3.0,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,21.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,Namrata,21.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [70]:
csv_1.fillna(method = 'bfill') #backward fill

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\3262113764.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method = 'bfill') #backward fill

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,5.0,85.0,78.0,90.0,Pokhara,Master
2,3,Sita,20.0,Female,5.0,80.0,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,20.0,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,5.0,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,96.0,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,20.0,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,6.0,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,6.0,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,18.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [72]:
csv_1.fillna(method='bfill',axis=1) # backward fill along column

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1168952258.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method='bfill',axis=1) # backward fill along column
C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1168952258.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv_1.fillna(method='bfill',axis=1) # backward fill along column

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,85.0,85.0,78.0,Pokhara,Pokhara,Master
2,3,Sita,Female,Female,5.0,92.0,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,Male,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,78.0,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,68.0,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,Female,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,81.0,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,76.0,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,Female,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [74]:
csv_1.fillna('python',limit=2) # fill null value with python where null value limit is 2

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,python,85.0,78.0,python,Pokhara,Master
2,3,Sita,python,Female,5.0,python,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,python,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,python,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,python,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,python,NaN,python,NaN,NaN,python,python,python,python
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

## Replace

In [111]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [81]:
csv_1.replace(to_replace=2.0,value ='22')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,22,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,22,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,22,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,22,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,22,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,22,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,22,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,22,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,22,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [91]:
csv_1.replace(to_replace='Anisha',value = 'python')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,python,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [93]:
csv_1.replace([1,2,3,4,5,6,7,8,9],10)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,10,Anisha,18.0,Female,10.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,10,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,10,Sita,NaN,Female,10.0,NaN,92.0,90.0,Butwal,Bachelor
3,10,Hari,20.0,Male,10.0,80.0,75.0,77.0,Lalitpur,High School
4,10,Gita,18.0,Female,10.0,95.0,94.0,96.0,Bhaktapur,Master
5,10,Bikash,21.0,Male,10.0,70.0,65.0,68.0,Chitwan,Bachelor
6,10,Nisha,19.0,Female,10.0,88.0,84.0,86.0,Pokhara,Bachelor
7,10,Rajan,NaN,Male,10.0,92.0,89.0,91.0,Kathmandu,Master
8,10,Pooja,20.0,Female,10.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,10.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,10.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,10.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,10.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,10.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,10.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,10.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,10.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,10.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,10.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,10.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,10.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,10.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,10.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,10.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,10.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,10.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,10.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,10.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,10.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,10.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,10.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,10.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,10.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,10.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,10.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,10.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,10.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,10.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,10.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,10.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,10.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,10.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,10.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,10.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,10.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,10.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [101]:
csv_1.replace('[A-Za-z]','python',regex=True)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,pythonpythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,4.0,90.0,85.0,88.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython
1,2,pythonpythonpython,19.0,pythonpythonpythonpython,NaN,85.0,78.0,NaN,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
2,3,pythonpythonpythonpython,NaN,pythonpythonpythonpythonpythonpython,5.0,NaN,92.0,90.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
3,4,pythonpythonpythonpython,20.0,pythonpythonpythonpython,3.0,80.0,75.0,77.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
4,5,pythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,6.0,95.0,94.0,96.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
5,6,pythonpythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,2.0,70.0,65.0,68.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
6,7,pythonpythonpythonpythonpython,19.0,pythonpythonpythonpythonpythonpython,4.0,88.0,84.0,86.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
7,8,pythonpythonpythonpythonpython,NaN,pythonpythonpythonpython,5.0,92.0,89.0,91.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
8,9,pythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,3.0,75.0,72.0,74.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
9,10,pythonpythonpythonpythonpython,18.0,pythonpythonpythonpython,4.0,85.0,80.0,82.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
10,11,pythonpythonpythonpythonpython,19.0,pythonpythonpythonpython,NaN,78.0,76.0,79.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
11,12,pythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,90.0,91.0,89.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
12,13,pythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,3.0,82.0,74.0,73.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
13,14,pythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,4.0,87.0,83.0,85.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython
14,15,pythonpythonpythonpythonpythonpython,19.0,pythonpythonpythonpython,2.0,NaN,68.0,70.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
15,16,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,6.0,96.0,95.0,97.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
16,17,pythonpythonpythonpythonpythonpython,22.0,pythonpythonpythonpython,4.0,84.0,81.0,80.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
17,18,pythonpythonpythonpythonpythonpython,NaN,pythonpythonpythonpythonpythonpython,5.0,89.0,88.0,90.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
18,19,pythonpythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpython,3.0,77.0,73.0,75.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
19,20,pythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,4.0,91.0,86.0,87.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
20,21,pythonpythonpythonpython,19.0,pythonpythonpythonpython,2.0,72.0,69.0,71.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
21,22,pythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,93.0,92.0,94.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
22,23,pythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,4.0,86.0,84.0,83.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
23,24,pythonpythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,3.0,79.0,77.0,76.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
24,25,pythonpythonpythonpythonpython,20.0,pythonpythonpythonpython,NaN,81.0,78.0,80.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
25,26,pythonpythonpythonpythonpythonpythonpython,19.0,pythonpythonpythonpythonpythonpython,6.0,97.0,96.0,98.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
26,27,pythonpythonpythonpythonpython,22.0,pythonpythonpythonpython,2.0,74.0,70.0,72.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
27,28,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,90.0,89.0,91.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
28,29,pythonpythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,3.0,83.0,79.0,81.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython
29,30,pythonpythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,4.0,88.0,85.0,84.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
30,31,pythonpythonpythonpythonpython,19.0,pythonpythonpythonpython,2.0,71.0,67.0,69.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
31,32,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,94.0,93.0,95.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
32,33,pythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,4.0,85.0,82.0,84.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
33,34,pythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,3.0,80.0,78.0,79.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpython pythonpythonpythonpyt...
34,35,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpython,NaN,76.0,74.0,73.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
35,36,pythonpythonpythonpythonpythonpythonpythonpython,19.0,pythonpythonpythonpythonpythonpython,6.0,98.0,97.0,99.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
36,37,pythonpythonpythonpythonpython,22.0,pythonpythonpythonpython,2.0,73.0,71.0,70.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
37,38,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,92.0,90.0,93.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
38,39,pythonpythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,4.0,84.0,81.0,82.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
39,40,pythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,3.0,78.0,75.0,77.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
40,41,pythonpythonpythonpythonpython,19.0,pythonpythonpythonpython,2.0,69.0,66.0,68.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython
41,42,pythonpythonpythonpythonpythonpython,20.0,pythonpythonpythonpythonpythonpython,5.0,95.0,94.0,96.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
42,43,pythonpythonpython,21.0,pythonpythonpythonpython,4.0,87.0,85.0,86.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython
43,44,pythonpythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,3.0,82.0,80.0,81.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpython pythonpythonpythonpyt...
44,45,pythonpythonpythonpythonpython,20.0,pythonpythonpythonpython,2.0,75.0,72.0,74.0,pythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
45,46,pythonpythonpythonpythonpython,19.0,pythonpythonpythonpythonpythonpython,6.0,97.0,95.0,98.0,pythonpythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpython
46,47,pythonpythonpythonpythonpython,21.0,pythonpythonpythonpython,4.0,88.0,86.0,87.0,pythonpythonpythonpythonpythonpythonpython,pythonpythonpythonpythonpythonpythonpythonpython
47,48,pythonpythonpythonpythonpythonpythonpython,NaN,pythonpythonpythonpythonpythonpython,5.0,91.0,90.0,92.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpython
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,pythonpythonpythonpythonpythonpythonpython,18.0,pythonpythonpythonpythonpythonpython,4.0,89.0,88.0,90.0,pythonpythonpythonpythonpythonpythonpythonpyth...,pythonpythonpythonpythonpythonpythonpythonpython

In [109]:
csv_1.replace({'Name':'[A-Za-z]'},'python',regex=True)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,pythonpythonpythonpythonpythonpython,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,pythonpythonpython,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,pythonpythonpythonpython,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,pythonpythonpythonpython,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,pythonpythonpythonpython,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,pythonpythonpythonpythonpythonpython,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,pythonpythonpythonpythonpython,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,pythonpythonpythonpythonpython,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,pythonpythonpythonpythonpython,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,pythonpythonpythonpythonpython,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,pythonpythonpythonpythonpython,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,pythonpythonpythonpython,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,pythonpythonpythonpythonpython,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,pythonpythonpythonpython,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,pythonpythonpythonpythonpythonpython,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,pythonpythonpythonpythonpythonpython,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,pythonpythonpythonpythonpythonpython,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,pythonpythonpythonpythonpythonpython,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,pythonpythonpythonpythonpythonpythonpython,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,pythonpythonpythonpythonpython,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,pythonpythonpythonpython,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,pythonpythonpythonpythonpython,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,pythonpythonpythonpythonpython,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,pythonpythonpythonpythonpythonpython,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,pythonpythonpythonpythonpython,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,pythonpythonpythonpythonpythonpythonpython,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,pythonpythonpythonpythonpython,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,pythonpythonpythonpythonpythonpython,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,pythonpythonpythonpythonpythonpython,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,pythonpythonpythonpythonpythonpython,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,pythonpythonpythonpythonpython,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,pythonpythonpythonpythonpythonpython,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,pythonpythonpythonpythonpython,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,pythonpythonpythonpythonpython,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,pythonpythonpythonpythonpythonpython,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,pythonpythonpythonpythonpythonpythonpythonpython,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,pythonpythonpythonpythonpython,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,pythonpythonpythonpythonpythonpython,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,pythonpythonpythonpythonpythonpython,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,pythonpythonpythonpythonpython,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,pythonpythonpythonpythonpython,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,pythonpythonpythonpythonpythonpython,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,pythonpythonpython,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,pythonpythonpythonpythonpythonpython,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,pythonpythonpythonpythonpython,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,pythonpythonpythonpythonpython,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,pythonpythonpythonpythonpython,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,pythonpythonpythonpythonpythonpythonpython,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,pythonpythonpythonpythonpythonpythonpython,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [117]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [115]:
csv_1.replace(2.0,method='ffill') #study hour column

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1872236509.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_1.replace(2.0,method='ffill')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,1,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,6.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,4.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,4.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,6.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,4.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,6.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,3.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,3.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [119]:
csv_1.replace(2.0,method='ffill',limit=2)

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1554443337.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_1.replace(2.0,method='ffill',limit=2)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,1,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,6.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,76.0,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,91.0,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,74.0,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,83.0,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,4.0,NaN,68.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,95.0,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,81.0,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,88.0,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,73.0,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,4.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,6.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,4.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,6.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,3.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,3.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

## interpolate

In [128]:
csv_1 = pd.read_csv("C:\\Users\\sampada\\machine-learning-journey\\pandas\\Student data.csv")
csv_1 ## remove value from mathsscore dataset

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,NaN,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,NaN,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,NaN,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,NaN,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,NaN,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,NaN,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,NaN,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,NaN,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,NaN,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [124]:
csv_1.interpolate()

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\3094693765.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate()

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.5,85.0,78.0,89.0,Pokhara,Master
2,3,Sita,19.5,Female,5.0,82.5,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.5,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.5,78.0,80.6,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,81.2,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,81.8,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,82.4,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,91.5,83.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,83.6,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,84.2,80.0,Butwal,Bachelor
17,18,Sarita,21.0,Female,5.0,89.0,84.8,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,85.4,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,4.5,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,4.5,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,20.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,19.0,NaN,4.5,90.0,89.0,91.0,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [126]:
csv_1.interpolate(method='linear')

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\3367518192.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(method='linear')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.5,85.0,78.0,89.0,Pokhara,Master
2,3,Sita,19.5,Female,5.0,82.5,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.5,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.5,78.0,80.6,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,81.2,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,81.8,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,82.4,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,91.5,83.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,83.6,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,84.2,80.0,Butwal,Bachelor
17,18,Sarita,21.0,Female,5.0,89.0,84.8,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,85.4,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,4.5,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,4.5,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,20.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,19.0,NaN,4.5,90.0,89.0,91.0,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [130]:
csv_1.interpolate(limit=2)

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\2529092742.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(limit=2)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.5,85.0,78.0,89.0,Pokhara,Master
2,3,Sita,19.5,Female,5.0,82.5,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.5,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.5,78.0,80.6,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,81.2,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,NaN,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,NaN,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,91.5,NaN,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,NaN,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,NaN,80.0,Butwal,Bachelor
17,18,Sarita,21.0,Female,5.0,89.0,NaN,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,NaN,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,4.5,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,4.5,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,20.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,19.0,NaN,4.5,90.0,89.0,91.0,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [134]:
csv_1.interpolate(limit_direction='forward',limit=2)#silimilar for backward and both

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1841410486.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(limit_direction='forward',limit=2)

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.5,85.0,78.0,89.0,Pokhara,Master
2,3,Sita,19.5,Female,5.0,82.5,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.5,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.5,78.0,80.6,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,81.2,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,NaN,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,NaN,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,91.5,NaN,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,NaN,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,NaN,80.0,Butwal,Bachelor
17,18,Sarita,21.0,Female,5.0,89.0,NaN,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,NaN,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,4.5,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,4.5,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,20.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,19.0,NaN,4.5,90.0,89.0,91.0,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [138]:
csv_1.interpolate(limit_area='inside') #fill all null value

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\1859058615.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(limit_area='inside')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,4.5,85.0,78.0,89.0,Pokhara,Master
2,3,Sita,19.5,Female,5.0,82.5,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,19.5,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,4.5,78.0,80.6,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,81.2,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,81.8,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,82.4,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,91.5,83.0,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,83.6,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,84.2,80.0,Butwal,Bachelor
17,18,Sarita,21.0,Female,5.0,89.0,84.8,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,85.4,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,4.5,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,4.5,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,20.0,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,19.0,NaN,4.5,90.0,89.0,91.0,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor

In [140]:
 csv_1.interpolate(limit_area='outside') #show all null value

C:\Users\sampada\AppData\Local\Temp\ipykernel_10356\2226505217.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  csv_1.interpolate(limit_area='outside')

,Student_ID,Name,Age,Gender,Study_Hours,Attendance,Math_Score,Science_Score,City,Parent_Education
0,1,Anisha,18.0,Female,4.0,90.0,85.0,88.0,Kathmandu,Bachelor
1,2,Ram,19.0,Male,NaN,85.0,78.0,NaN,Pokhara,Master
2,3,Sita,NaN,Female,5.0,NaN,92.0,90.0,Butwal,Bachelor
3,4,Hari,20.0,Male,3.0,80.0,75.0,77.0,Lalitpur,High School
4,5,Gita,18.0,Female,6.0,95.0,94.0,96.0,Bhaktapur,Master
5,6,Bikash,21.0,Male,2.0,70.0,65.0,68.0,Chitwan,Bachelor
6,7,Nisha,19.0,Female,4.0,88.0,84.0,86.0,Pokhara,Bachelor
7,8,Rajan,NaN,Male,5.0,92.0,89.0,91.0,Kathmandu,Master
8,9,Pooja,20.0,Female,3.0,75.0,72.0,74.0,Butwal,High School
9,10,Suman,18.0,Male,4.0,85.0,80.0,82.0,Dharan,Bachelor
10,11,Kiran,19.0,Male,NaN,78.0,NaN,79.0,Lalitpur,Bachelor
11,12,Rita,20.0,Female,5.0,90.0,NaN,89.0,Bhaktapur,Master
12,13,Ashok,21.0,Male,3.0,82.0,NaN,73.0,Chitwan,High School
13,14,Mina,18.0,Female,4.0,87.0,NaN,85.0,Kathmandu,Bachelor
14,15,Deepak,19.0,Male,2.0,NaN,NaN,70.0,Pokhara,High School
15,16,Sabina,20.0,Female,6.0,96.0,NaN,97.0,Dharan,Master
16,17,Ramesh,22.0,Male,4.0,84.0,NaN,80.0,Butwal,Bachelor
17,18,Sarita,NaN,Female,5.0,89.0,NaN,90.0,Lalitpur,Bachelor
18,19,Prakash,20.0,Male,3.0,77.0,NaN,75.0,Chitwan,High School
19,20,Rekha,18.0,Female,4.0,91.0,86.0,87.0,Bhaktapur,Master
20,21,Ajay,19.0,Male,2.0,72.0,69.0,71.0,Dharan,Bachelor
21,22,Sneha,20.0,Female,5.0,93.0,92.0,94.0,Kathmandu,Master
22,23,Nabin,21.0,Male,4.0,86.0,84.0,83.0,Pokhara,Bachelor
23,24,Sunita,18.0,Female,3.0,79.0,77.0,76.0,Butwal,High School
24,25,Rohit,20.0,Male,NaN,81.0,78.0,80.0,Lalitpur,Bachelor
25,26,Manisha,19.0,Female,6.0,97.0,96.0,98.0,Bhaktapur,Master
26,27,Arjun,22.0,Male,2.0,74.0,70.0,72.0,Chitwan,High School
27,28,Kabita,20.0,Female,5.0,90.0,89.0,91.0,Dharan,Bachelor
28,29,Suresh,21.0,Male,3.0,83.0,79.0,81.0,Kathmandu,Bachelor
29,30,Asmita,18.0,Female,4.0,88.0,85.0,84.0,Pokhara,Master
30,31,Binod,19.0,Male,2.0,71.0,67.0,69.0,Butwal,High School
31,32,Roshni,20.0,Female,5.0,94.0,93.0,95.0,Lalitpur,Master
32,33,Shyam,21.0,Male,4.0,85.0,82.0,84.0,Chitwan,Bachelor
33,34,Alina,18.0,Female,3.0,80.0,78.0,79.0,Bhaktapur,High School
34,35,Dinesh,20.0,Male,NaN,76.0,74.0,73.0,Dharan,Bachelor
35,36,Priyanka,19.0,Female,6.0,98.0,97.0,99.0,Kathmandu,Master
36,37,Madan,22.0,Male,2.0,73.0,71.0,70.0,Pokhara,High School
37,38,Shreya,20.0,Female,5.0,92.0,90.0,93.0,Butwal,Bachelor
38,39,Ganesh,21.0,Male,4.0,84.0,81.0,82.0,Lalitpur,Bachelor
39,40,Laxmi,18.0,Female,3.0,78.0,75.0,77.0,Chitwan,High School
40,41,Niraj,19.0,Male,2.0,69.0,66.0,68.0,Bhaktapur,Bachelor
41,42,Sushma,20.0,Female,5.0,95.0,94.0,96.0,Dharan,Master
42,43,Tej,21.0,Male,4.0,87.0,85.0,86.0,Kathmandu,Bachelor
43,44,Reshma,18.0,Female,3.0,82.0,80.0,81.0,Pokhara,High School
44,45,Kamal,20.0,Male,2.0,75.0,72.0,74.0,Butwal,Bachelor
45,46,Aarti,19.0,Female,6.0,97.0,95.0,98.0,Lalitpur,Master
46,47,Suraj,21.0,Male,4.0,88.0,86.0,87.0,Chitwan,Bachelor
47,48,Namrata,NaN,Female,5.0,91.0,90.0,92.0,Bhaktapur,Master
48,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,Pratima,18.0,Female,4.0,89.0,88.0,90.0,Kathmandu,Bachelor