## Merge

In [5]:
import pandas as pd

In [27]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,4],'c':[21,22,23,24]})
pd.merge(var1,var2,on ='A')

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [29]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='left')

   A   B     c
0  1  11  21.0
1  2  12  22.0
2  3  13  23.0
3  4  14   NaN

In [31]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='right')

   A     B   c
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  5   NaN  24

In [37]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='right',indicator=True)

   A     B   c      _merge
0  1  11.0  21        both
1  2  12.0  22        both
2  3  13.0  23        both
3  5   NaN  24  right_only

In [39]:
pd.merge(var1,var2,how ='left',indicator=True)

   A   B     c     _merge
0  1  11  21.0       both
1  2  12  22.0       both
2  3  13  23.0       both
3  4  14   NaN  left_only

In [45]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,4],'B':[21,22,23,24]})
pd.merge(var1,var2,left_index = True,right_index = True)#when same name

   A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    4   24

In [47]:
pd.merge(var1,var2,left_index = True,right_index = True,suffixes=('name','id'))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    4   24

## Concat

In [54]:
s1= pd.Series([1,2,3,4])
s2= pd.Series([21,22,23,24])
pd.concat([s1,s2])

0     1
1     2
2     3
3     4
0    21
1    22
2    23
3    24
dtype: int64

In [56]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'B':[21,22,23,24]})
pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  24
0  1  21
1  2  22
2  3  23
3  5  24

In [58]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'B':[21,22,23,24]})
pd.concat([d1,d2],axis=1)

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  24  5  24

In [64]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2],'B':[21,22]})
pd.concat([d1,d2],axis=1,join='inner')#intersection

   A   B  A   B
0  1  11  1  21
1  2  12  2  22

In [66]:
pd.concat([d1,d2],axis=1,join='outer')#union

   A   B    A     B
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  24  NaN   NaN

In [70]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.concat([d1,d2],axis=1,keys=['d1','d2'])

  d1     d2
   A   B  A   c
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  24  5  24

In [72]:
pd.concat([d1,d2],axis=0,keys=['d1','d2'])

      A     B     c
d1 0  1  11.0   NaN
   1  2  12.0   NaN
   2  3  13.0   NaN
   3  4  24.0   NaN
d2 0  1   NaN  21.0
   1  2   NaN  22.0
   2  3   NaN  23.0
   3  5   NaN  24.0

## GroupBY

In [81]:
var = pd.DataFrame({'name':['a','b','c','a','c','b','c','a','b','a'],
                    's1':[12,13,14,23,12,15,13,12,24,23],
                    's2':[22,23,24,22,12,24,23,12,22,24]})
var

  name  s1  s2
0    a  12  22
1    b  13  23
2    c  14  24
3    a  23  22
4    c  12  12
5    b  15  24
6    c  13  23
7    a  12  12
8    b  24  22
9    a  23  24

In [83]:
var_new  = var.groupby('name')
var_new

In [87]:
for x,y in var_new:
    print(x)
  
    print(y)
    print()

a
  name  s1  s2
0    a  12  22
3    a  23  22
7    a  12  12
9    a  23  24

b
  name  s1  s2
1    b  13  23
5    b  15  24
8    b  24  22

c
  name  s1  s2
2    c  14  24
4    c  12  12
6    c  13  23

In [89]:
var_new.get_group('a')

  name  s1  s2
0    a  12  22
3    a  23  22
7    a  12  12
9    a  23  24

In [91]:
var_new.min()

      s1  s2
name
a     12  12
b     13  22
c     12  12

In [93]:
var_new.min()

      s1  s2
name
a     12  12
b     13  22
c     12  12

In [95]:
li = list(var_new)
li

[('a',
    name  s1  s2
  0    a  12  22
  3    a  23  22
  7    a  12  12
  9    a  23  24),
 ('b',
    name  s1  s2
  1    b  13  23
  5    b  15  24
  8    b  24  22),
 ('c',
    name  s1  s2
  2    c  14  24
  4    c  12  12
  6    c  13  23)]