## Merge

In [5]:
import pandas as pd

In [27]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,4],'c':[21,22,23,24]})
pd.merge(var1,var2,on ='A')

   A   B   c
0  1  11  21
1  2  12  22
2  3  13  23
3  4  14  24

In [29]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='left')

   A   B     c
0  1  11  21.0
1  2  12  22.0
2  3  13  23.0
3  4  14   NaN

In [31]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='right')

   A     B   c
0  1  11.0  21
1  2  12.0  22
2  3  13.0  23
3  5   NaN  24

In [37]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.merge(var1,var2,how ='right',indicator=True)

   A     B   c      _merge
0  1  11.0  21        both
1  2  12.0  22        both
2  3  13.0  23        both
3  5   NaN  24  right_only

In [39]:
pd.merge(var1,var2,how ='left',indicator=True)

   A   B     c     _merge
0  1  11  21.0       both
1  2  12  22.0       both
2  3  13  23.0       both
3  4  14   NaN  left_only

In [45]:
var1 =pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,14]})
var2 =pd.DataFrame({'A':[1,2,3,4],'B':[21,22,23,24]})
pd.merge(var1,var2,left_index = True,right_index = True)#when same name

   A_x  B_x  A_y  B_y
0    1   11    1   21
1    2   12    2   22
2    3   13    3   23
3    4   14    4   24

In [47]:
pd.merge(var1,var2,left_index = True,right_index = True,suffixes=('name','id'))

   Aname  Bname  Aid  Bid
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    4   24

## Concat

In [54]:
s1= pd.Series([1,2,3,4])
s2= pd.Series([21,22,23,24])
pd.concat([s1,s2])

0     1
1     2
2     3
3     4
0    21
1    22
2    23
3    24
dtype: int64

In [56]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'B':[21,22,23,24]})
pd.concat([d1,d2])

   A   B
0  1  11
1  2  12
2  3  13
3  4  24
0  1  21
1  2  22
2  3  23
3  5  24

In [58]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'B':[21,22,23,24]})
pd.concat([d1,d2],axis=1)

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  24  5  24

In [64]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2],'B':[21,22]})
pd.concat([d1,d2],axis=1,join='inner')#intersection

   A   B  A   B
0  1  11  1  21
1  2  12  2  22

In [66]:
pd.concat([d1,d2],axis=1,join='outer')#union

   A   B    A     B
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  24  NaN   NaN

In [70]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2,3,5],'c':[21,22,23,24]})
pd.concat([d1,d2],axis=1,keys=['d1','d2'])

  d1     d2
   A   B  A   c
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  24  5  24

In [72]:
pd.concat([d1,d2],axis=0,keys=['d1','d2'])

      A     B     c
d1 0  1  11.0   NaN
   1  2  12.0   NaN
   2  3  13.0   NaN
   3  4  24.0   NaN
d2 0  1   NaN  21.0
   1  2   NaN  22.0
   2  3   NaN  23.0
   3  5   NaN  24.0

## GroupBY

In [81]:
var = pd.DataFrame({'name':['a','b','c','a','c','b','c','a','b','a'],
                    's1':[12,13,14,23,12,15,13,12,24,23],
                    's2':[22,23,24,22,12,24,23,12,22,24]})
var

  name  s1  s2
0    a  12  22
1    b  13  23
2    c  14  24
3    a  23  22
4    c  12  12
5    b  15  24
6    c  13  23
7    a  12  12
8    b  24  22
9    a  23  24

In [83]:
var_new  = var.groupby('name')
var_new

In [87]:
for x,y in var_new:
    print(x)
  
    print(y)
    print()

a
  name  s1  s2
0    a  12  22
3    a  23  22
7    a  12  12
9    a  23  24

b
  name  s1  s2
1    b  13  23
5    b  15  24
8    b  24  22

c
  name  s1  s2
2    c  14  24
4    c  12  12
6    c  13  23

In [89]:
var_new.get_group('a')

  name  s1  s2
0    a  12  22
3    a  23  22
7    a  12  12
9    a  23  24

In [91]:
var_new.min()

      s1  s2
name
a     12  12
b     13  22
c     12  12

In [93]:
var_new.min()

      s1  s2
name
a     12  12
b     13  22
c     12  12

In [95]:
li = list(var_new)
li

[('a',
    name  s1  s2
  0    a  12  22
  3    a  23  22
  7    a  12  12
  9    a  23  24),
 ('b',
    name  s1  s2
  1    b  13  23
  5    b  15  24
  8    b  24  22),
 ('c',
    name  s1  s2
  2    c  14  24
  4    c  12  12
  6    c  13  23)]

## join

In [100]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'C':[1,2,3,5],'D':[21,22,23,24]})
d1.join(d2)

   A   B  C   D
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  24  5  24

In [102]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'C':[1,2],'D':[21,22]})
d1.join(d2)

   A   B    C     D
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  24  NaN   NaN

In [104]:
d1.join(d2,how = 'inner')

   A   B  C   D
0  1  11  1  21
1  2  12  2  22

In [106]:
d1.join(d2,how = 'outer')

   A   B    C     D
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  24  NaN   NaN

In [108]:
d1.join(d2,how = 'left')

   A   B    C     D
0  1  11  1.0  21.0
1  2  12  2.0  22.0
2  3  13  NaN   NaN
3  4  24  NaN   NaN

In [110]:
d1.join(d2,how = 'right')

   A   B  C   D
0  1  11  1  21
1  2  12  2  22

In [120]:
d1= pd.DataFrame({'A':[1,2,3,4],'B':[11,12,13,24]})
d2 = pd.DataFrame({'A':[1,2],'B':[21,22]})# column name same then value eror us raised to remove this suffix is used
d1.join(d2,how = 'left',lsuffix = '_12')

   A_12  B_12    A     B
0     1    11  1.0  21.0
1     2    12  2.0  22.0
2     3    13  NaN   NaN
3     4    24  NaN   NaN

In [124]:
d1.join(d2,rsuffix = '_12')

   A   B  A_12  B_12
0  1  11   1.0  21.0
1  2  12   2.0  22.0
2  3  13   NaN   NaN
3  4  24   NaN   NaN

## Reshaping using melt() n pivot()

### melt()

In [139]:
var = pd.DataFrame({'Days':[1,2,3,4,5,6],'eng':[11,12,13,14,15,16],'sci':[17,18,19,20,12,23]})
var

   Days  eng  sci
0     1   11   17
1     2   12   18
2     3   13   19
3     4   14   20
4     5   15   12
5     6   16   23

In [141]:
pd.melt(var)# represnt data vertivally

   variable  value
0      Days      1
1      Days      2
2      Days      3
3      Days      4
4      Days      5
5      Days      6
6       eng     11
7       eng     12
8       eng     13
9       eng     14
10      eng     15
11      eng     16
12      sci     17
13      sci     18
14      sci     19
15      sci     20
16      sci     12
17      sci     23

In [143]:
pd.melt(var,id_vars=['Days'])

    Days variable  value
0      1      eng     11
1      2      eng     12
2      3      eng     13
3      4      eng     14
4      5      eng     15
5      6      eng     16
6      1      sci     17
7      2      sci     18
8      3      sci     19
9      4      sci     20
10     5      sci     12
11     6      sci     23

In [147]:
pd.melt(var,id_vars=['eng'],var_name ='python')

    eng python  value
0    11   Days      1
1    12   Days      2
2    13   Days      3
3    14   Days      4
4    15   Days      5
5    16   Days      6
6    11    sci     17
7    12    sci     18
8    13    sci     19
9    14    sci     20
10   15    sci     12
11   16    sci     23

In [151]:
pd.melt(var,id_vars=['eng'],var_name ='python',value_name = 'val')

    eng python  val
0    11   Days    1
1    12   Days    2
2    13   Days    3
3    14   Days    4
4    15   Days    5
5    16   Days    6
6    11    sci   17
7    12    sci   18
8    13    sci   19
9    14    sci   20
10   15    sci   12
11   16    sci   23

### pivot()

In [156]:
var = pd.DataFrame({'Days':[1,2,3,4,5,6],'st_name':['a','b','c','a','b','c'],'eng':[11,12,13,14,15,16],'sci':[17,18,19,20,12,23]})
var

   Days st_name  eng  sci
0     1       a   11   17
1     2       b   12   18
2     3       c   13   19
3     4       a   14   20
4     5       b   15   12
5     6       c   16   23

In [158]:
var.pivot(index='Days',columns = 'st_name')

          eng               sci
st_name     a     b     c     a     b     c
Days
1        11.0   NaN   NaN  17.0   NaN   NaN
2         NaN  12.0   NaN   NaN  18.0   NaN
3         NaN   NaN  13.0   NaN   NaN  19.0
4        14.0   NaN   NaN  20.0   NaN   NaN
5         NaN  15.0   NaN   NaN  12.0   NaN
6         NaN   NaN  16.0   NaN   NaN  23.0

In [162]:
var.pivot(index='Days',columns = 'st_name',values = 'eng')# to get only one column data

st_name     a     b     c
Days
1        11.0   NaN   NaN
2         NaN  12.0   NaN
3         NaN   NaN  13.0
4        14.0   NaN   NaN
5         NaN  15.0   NaN
6         NaN   NaN  16.0

In [164]:
var = pd.DataFrame({'Days':[1,1,1,1,2,2],'st_name':['a','b','c','a','b','c'],'eng':[11,12,13,14,15,16],'sci':[17,18,19,20,12,23]})
var

   Days st_name  eng  sci
0     1       a   11   17
1     1       b   12   18
2     1       c   13   19
3     1       a   14   20
4     2       b   15   12
5     2       c   16   23

In [172]:
var.pivot_table(index = 'st_name',columns ='Days',aggfunc= 'mean')

          eng         sci
Days        1     2     1     2
st_name
a        12.5   NaN  18.5   NaN
b        12.0  15.0  18.0  12.0
c        13.0  16.0  19.0  23.0

In [174]:
var.pivot_table(index = 'st_name',columns ='Days',aggfunc= 'sum')

          eng         sci
Days        1     2     1     2
st_name
a        25.0   NaN  37.0   NaN
b        12.0  15.0  18.0  12.0
c        13.0  16.0  19.0  23.0

In [176]:
var.pivot_table(index = 'st_name',columns ='Days',aggfunc= 'sum',margins =True)# margin gives mean

          eng             sci
Days        1     2 All     1     2  All
st_name
a        25.0   NaN  25  37.0   NaN   37
b        12.0  15.0  27  18.0  12.0   30
c        13.0  16.0  29  19.0  23.0   42
All      50.0  31.0  81  74.0  35.0  109